### ISSUE TITLE
Unicode error in log

### ISSUE THREAD

**Issue by pcolton** [aydinyanik/clarisse_survival_kit#33]
I get this log error trying any button in the toolset.

![Screenshot 2022-03-31 193837](https://user-images.githubusercontent.com/92073/161184440-5433a39b-399b-4506-9c70-f01e01a17232.png)

**Comment by pcolton** [comment]
It seems if I edit the file in question and double-backslash all the backslashes, it works. Ideally the installer would do this by default on Windows.

**Comment by aydinyanik** [comment]
Hi Paul. Yeah you're correct about the filename. I forgot to make the string raw so the slashes are ignored. I pushed the fix, but you don't need to reinstall it because you've already fixed it by hand.

I might change the setup a bit in the future because having mixed Python2 and 3 versions installed can lead to some small install issues also.
